@startuml
title Activity Diagram 

start
:Користувач надсилає запит на отрмання консультації щодо фізичного здоров'я;
if (Успішно?) then (Так)
  :Доктор відповідає на запит;
  :Доктор зв'язується з користувачем;
  if (Успішно?) then (Так)
    :Користувач отримує консультацію;
  else (Ні)
    :Повідомлення про помилку;
  endif
else (Ні)
  :Очікування відповіді;
endif
stop

@enduml